import { Router, Request, Response } from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import sharp from 'sharp';
import { prisma } from '../db';

// These types will be generated by `prisma generate` once the migration is applied.
// Until then the Prisma client doesn't know about the new models, so we cast to any.
type InvoiceStatus = 'DRAFT' | 'CONFIRMED' | 'PAID';
type InvoiceType = 'OWNER' | 'STABLE';
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = prisma as any;
import { authenticate } from '../middleware/auth';
import { AuthRequest } from '../types';

const router = Router();

// ─── File upload setup (shared with health records) ──────────

const recordUploadsDir = path.join(process.cwd(), 'uploads', 'records');
fs.mkdirSync(recordUploadsDir, { recursive: true });

const IMAGE_MIME_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif']);
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.heic', '.heif']);

const invoiceUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 20 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    if (IMAGE_EXTENSIONS.has(ext) || IMAGE_MIME_TYPES.has(file.mimetype) || ext === '.pdf') {
      cb(null, true);
    } else {
      cb(new Error('Only images and PDF files are allowed'));
    }
  },
});

async function handleFileUpload(req: Request, res: Response): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    invoiceUpload.single('file')(req, res, (err) => {
      if (err) {
        const msg = err instanceof multer.MulterError
          ? `Upload error: ${err.message}`
          : err.message || 'Upload failed';
        reject(new Error(msg));
      } else {
        resolve();
      }
    });
  });

  if (!req.file) return;

  const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
  const ext = path.extname(req.file.originalname).toLowerCase();
  const isImage = IMAGE_MIME_TYPES.has(req.file.mimetype) || IMAGE_EXTENSIONS.has(ext);

  if (isImage) {
    const filename = `${uniqueSuffix}.webp`;
    await sharp(req.file.buffer)
      .resize(1600, 1600, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 85 })
      .toFile(path.join(recordUploadsDir, filename));
    req.file.filename = filename;
  } else {
    const filename = `${uniqueSuffix}.pdf`;
    fs.writeFileSync(path.join(recordUploadsDir, filename), req.file.buffer);
    req.file.filename = filename;
  }
}

function getFileInfo(req: Request): { fileUrl: string | null; fileName: string | null } {
  if (req.file) {
    return {
      fileUrl: `/api/uploads/records/${req.file.filename}`,
      fileName: req.file.originalname,
    };
  }
  return { fileUrl: null, fileName: null };
}

// ─── Selects ──────────────────────────────────────────────────

const INVOICE_SELECT = {
  id: true,
  type: true,
  supplier: true,
  category: true,
  date: true,
  totalAmount: true,
  notes: true,
  fileUrl: true,
  fileName: true,
  status: true,
  stableId: true,
  createdAt: true,
  updatedAt: true,
  createdBy: { select: { id: true, name: true, email: true } },
  stable: { select: { id: true, name: true } },
  splits: {
    select: {
      id: true,
      horseId: true,
      ownerId: true,
      amount: true,
      horse: { select: { id: true, name: true } },
      owner: { select: { id: true, name: true, email: true } },
    },
  },
} as const;

// ─── Access helpers ───────────────────────────────────────────

async function getAccessibleHorseIds(userId: string, role: string): Promise<string[]> {
  if (role === 'ADMIN') {
    const horses = await prisma.horse.findMany({ select: { id: true } });
    return horses.map((h) => h.id);
  }
  const [assignments, stableAssignments] = await Promise.all([
    prisma.horseAssignment.findMany({ where: { userId }, select: { horseId: true } }),
    prisma.stableAssignment.findMany({ where: { userId }, select: { stableId: true } }),
  ]);
  const stableHorses = stableAssignments.length > 0
    ? await prisma.horse.findMany({
        where: { stableId: { in: stableAssignments.map((s) => s.stableId) } },
        select: { id: true },
      })
    : [];
  return [...new Set([
    ...assignments.map((a) => a.horseId),
    ...stableHorses.map((h) => h.id),
  ])];
}

// ─── Routes ───────────────────────────────────────────────────

// GET /api/invoices — list invoices visible to current user
router.get('/', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const userId = req.user!.userId;
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) { res.status(401).json({ error: 'User not found' }); return; }

    const { status, category, from, to, horseId } = req.query;

    let whereCondition: Record<string, unknown> = {};

    if (user.role === 'ADMIN') {
      // Admin sees everything
      whereCondition = {};
    } else if (user.role === 'STABLE_LEAD') {
      // Stable lead sees invoices for their stable(s) or invoices they created
      const stableAssignments = await prisma.stableAssignment.findMany({
        where: { userId },
        select: { stableId: true },
      });
      const stableIds = stableAssignments.map((s) => s.stableId);
      whereCondition = {
        OR: [
          { createdById: userId },
          { stableId: { in: stableIds } },
          { splits: { some: { horse: { stableId: { in: stableIds } } } } },
        ],
      };
    } else {
      // Owner/Trainer: sees invoices where their horses are in the splits, or they created
      const horseIds = await getAccessibleHorseIds(userId, user.role);
      whereCondition = {
        OR: [
          { createdById: userId },
          { splits: { some: { horseId: { in: horseIds } } } },
          { splits: { some: { ownerId: userId } } },
        ],
      };
    }

    if (status) whereCondition.status = status as InvoiceStatus;
    if (category) whereCondition.category = category as string;
    if (horseId) {
      whereCondition = {
        ...whereCondition,
        splits: { some: { horseId: horseId as string } },
      };
    }
    if (from || to) {
      whereCondition.date = {
        ...(from ? { gte: new Date(from as string) } : {}),
        ...(to ? { lte: new Date(to as string) } : {}),
      };
    }

    const invoices = await db.invoice.findMany({
      where: whereCondition,
      orderBy: { date: 'desc' },
      select: INVOICE_SELECT,
    });

    res.json(invoices);
  } catch (err) {
    console.error('List invoices error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/invoices/horse/:horseId — invoices for a specific horse
router.get('/horse/:horseId', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const { horseId } = req.params;
    const userId = req.user!.userId;
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) { res.status(401).json({ error: 'User not found' }); return; }

    // Verify access to this horse
    const accessibleIds = await getAccessibleHorseIds(userId, user.role);
    if (!accessibleIds.includes(horseId)) {
      res.status(403).json({ error: 'No access to this horse' });
      return;
    }

    const invoices = await db.invoice.findMany({
      where: { splits: { some: { horseId } } },
      orderBy: { date: 'desc' },
      select: INVOICE_SELECT,
    });

    res.json(invoices);
  } catch (err) {
    console.error('List horse invoices error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/invoices/costs/summary — aggregated cost data for dashboard
router.get('/costs/summary', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const userId = req.user!.userId;
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) { res.status(401).json({ error: 'User not found' }); return; }

    const { year, horseId } = req.query;
    const targetYear = year ? parseInt(year as string) : new Date().getFullYear();

    const yearStart = new Date(`${targetYear}-01-01`);
    const yearEnd = new Date(`${targetYear}-12-31`);

    // Get accessible horse IDs
    const accessibleHorseIds = await getAccessibleHorseIds(userId, user.role);
    const filteredHorseIds = horseId
      ? [horseId as string].filter((id) => accessibleHorseIds.includes(id))
      : accessibleHorseIds;

    // Fetch all splits for accessible horses within the year
    const splits = await db.invoiceSplit.findMany({
      where: {
        horseId: { in: filteredHorseIds },
        invoice: { date: { gte: yearStart, lte: yearEnd }, status: { not: 'DRAFT' } },
      },
      select: {
        amount: true,
        horseId: true,
        invoice: {
          select: {
            id: true,
            category: true,
            date: true,
            type: true,
            status: true,
          },
        },
      },
    });

    // Also include per-horse ExpenseNotes (legacy)
    const expenseNotes = await prisma.expenseNote.findMany({
      where: {
        horseId: { in: filteredHorseIds },
        date: { gte: yearStart, lte: yearEnd },
        amount: { not: null },
      },
      select: {
        horseId: true,
        amount: true,
        category: true,
        date: true,
      },
    });

    // Get horse names
    const horses = await prisma.horse.findMany({
      where: { id: { in: filteredHorseIds } },
      select: { id: true, name: true },
    });

    const horseMap = new Map(horses.map((h) => [h.id, h.name]));

    // Monthly breakdown per horse (from invoice splits)
    type MonthData = { month: number; amount: number };
    type CategoryData = { category: string; amount: number };

    const perHorse: Record<string, {
      horseId: string;
      horseName: string;
      totalAmount: number;
      byMonth: MonthData[];
      byCategory: CategoryData[];
    }> = {};

    for (const horseId of filteredHorseIds) {
      perHorse[horseId] = {
        horseId,
        horseName: horseMap.get(horseId) || 'Unknown',
        totalAmount: 0,
        byMonth: Array.from({ length: 12 }, (_, i) => ({ month: i + 1, amount: 0 })),
        byCategory: [],
      };
    }

    const categoryTotals: Record<string, Record<string, number>> = {};

    for (const split of splits) {
      const hId = split.horseId;
      const amount = parseFloat(split.amount.toString());
      const month = new Date(split.invoice.date).getMonth(); // 0-indexed
      const category = split.invoice.category;

      if (perHorse[hId]) {
        perHorse[hId].totalAmount += amount;
        perHorse[hId].byMonth[month].amount += amount;
      }

      if (!categoryTotals[hId]) categoryTotals[hId] = {};
      categoryTotals[hId][category] = (categoryTotals[hId][category] || 0) + amount;
    }

    for (const note of expenseNotes) {
      const hId = note.horseId;
      const amount = parseFloat(note.amount!.toString());
      const month = new Date(note.date).getMonth();
      const category = note.category || 'Other';

      if (perHorse[hId]) {
        perHorse[hId].totalAmount += amount;
        perHorse[hId].byMonth[month].amount += amount;
      }

      if (!categoryTotals[hId]) categoryTotals[hId] = {};
      categoryTotals[hId][category] = (categoryTotals[hId][category] || 0) + amount;
    }

    // Convert category totals to arrays
    for (const hId of Object.keys(perHorse)) {
      perHorse[hId].byCategory = Object.entries(categoryTotals[hId] || {}).map(
        ([category, amount]) => ({ category, amount })
      ).sort((a, b) => b.amount - a.amount);
    }

    // Grand total by month (across all horses)
    const grandByMonth = Array.from({ length: 12 }, (_, i) => {
      const amount = Object.values(perHorse).reduce(
        (sum, h) => sum + h.byMonth[i].amount, 0
      );
      return { month: i + 1, amount };
    });

    const grandTotal = Object.values(perHorse).reduce((sum, h) => sum + h.totalAmount, 0);

    res.json({
      year: targetYear,
      grandTotal,
      grandByMonth,
      horses: Object.values(perHorse),
    });
  } catch (err) {
    console.error('Cost summary error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/invoices/:id
router.get('/:id', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const invoice = await db.invoice.findUnique({
      where: { id: req.params.id },
      select: INVOICE_SELECT,
    });
    if (!invoice) { res.status(404).json({ error: 'Not found' }); return; }
    res.json(invoice);
  } catch (err) {
    console.error('Get invoice error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/invoices — create invoice with splits
router.post('/', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    await handleFileUpload(req, res);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Upload failed';
    res.status(400).json({ error: msg });
    return;
  }

  try {
    const userId = req.user!.userId;
    const { type, supplier, category, date, totalAmount, notes, status, stableId, splits } = req.body;

    if (!category || !date || !totalAmount) {
      res.status(400).json({ error: 'category, date, and totalAmount are required' });
      return;
    }

    const parsedSplits: { horseId: string; ownerId?: string; amount: number }[] =
      typeof splits === 'string' ? JSON.parse(splits) : splits;

    if (!parsedSplits || parsedSplits.length === 0) {
      res.status(400).json({ error: 'At least one split is required' });
      return;
    }

    const { fileUrl, fileName } = getFileInfo(req);

    const invoice = await db.invoice.create({
      data: {
        type: (type as InvoiceType) || 'OWNER',
        createdById: userId,
        stableId: stableId || null,
        supplier: supplier || null,
        category,
        date: new Date(date + 'T00:00:00Z'),
        totalAmount: parseFloat(totalAmount),
        notes: notes || null,
        fileUrl,
        fileName,
        status: (status as InvoiceStatus) || 'CONFIRMED',
        splits: {
          create: parsedSplits.map((s) => ({
            horseId: s.horseId,
            ownerId: s.ownerId || null,
            amount: s.amount,
          })),
        },
      },
      select: INVOICE_SELECT,
    });

    res.status(201).json(invoice);
  } catch (err) {
    console.error('Create invoice error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PUT /api/invoices/:id — update invoice (replaces splits)
router.put('/:id', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    await handleFileUpload(req, res);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Upload failed';
    res.status(400).json({ error: msg });
    return;
  }

  try {
    const existing = await db.invoice.findUnique({ where: { id: req.params.id } });
    if (!existing) { res.status(404).json({ error: 'Not found' }); return; }

    const { supplier, category, date, totalAmount, notes, status, splits } = req.body;

    const parsedSplits: { horseId: string; ownerId?: string; amount: number }[] | undefined =
      splits ? (typeof splits === 'string' ? JSON.parse(splits) : splits) : undefined;

    const { fileUrl, fileName } = getFileInfo(req);

    // Rebuild splits if provided
    const splitsUpdate = parsedSplits
      ? {
          deleteMany: {},
          create: parsedSplits.map((s) => ({
            horseId: s.horseId,
            ownerId: s.ownerId || null,
            amount: s.amount,
          })),
        }
      : undefined;

    const invoice = await db.invoice.update({
      where: { id: req.params.id },
      data: {
        supplier: supplier !== undefined ? supplier || null : undefined,
        category: category || undefined,
        date: date ? new Date(date + 'T00:00:00Z') : undefined,
        totalAmount: totalAmount ? parseFloat(totalAmount) : undefined,
        notes: notes !== undefined ? notes || null : undefined,
        status: status ? (status as InvoiceStatus) : undefined,
        fileUrl: fileUrl || existing.fileUrl,
        fileName: fileName || existing.fileName,
        ...(splitsUpdate ? { splits: splitsUpdate } : {}),
      },
      select: INVOICE_SELECT,
    });

    res.json(invoice);
  } catch (err) {
    console.error('Update invoice error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// PATCH /api/invoices/:id/status — quick status update
router.patch('/:id/status', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    const { status } = req.body;
    if (!status) { res.status(400).json({ error: 'status required' }); return; }
    const invoice = await db.invoice.update({
      where: { id: req.params.id },
      data: { status: status as InvoiceStatus },
      select: INVOICE_SELECT,
    });
    res.json(invoice);
  } catch {
    res.status(404).json({ error: 'Not found' });
  }
});

// DELETE /api/invoices/:id
router.delete('/:id', authenticate, async (req: AuthRequest, res: Response) => {
  try {
    await db.invoice.delete({ where: { id: req.params.id } });
    res.json({ message: 'Deleted' });
  } catch {
    res.status(404).json({ error: 'Not found' });
  }
});

export default router;
